### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LucaGabi** [CodeMazeBlog/swagger-ui-asp-net-core#1]
Hi, I downloaded the zip from the repo and run from VS2019 CE and it dose not work.

Can you help me, please ?

![image](https://user-images.githubusercontent.com/37976898/71973700-53843a80-3218-11ea-9aa4-e0b9ea0a18d6.png)

**Comment by MarinkoSpasojevic** [comment]
Hello LucaGabi. 

You are targeting the wrong link. Please take a look at this picture:

![image](https://user-images.githubusercontent.com/36244468/71986567-fb0b6800-322c-11ea-9e15-d8d2dcbe01a1.png)

Additionally, please read our complete article on https://code-maze.com/swagger-ui-asp-net-core-web-api/  

You will find a lot of useful information there.
